pipeline {
    agent none // Individual agents are handled inside each stage

    stages {    
        stage('Back-end') {
            agent { 
                // REMOVED THE SPACE HERE
                docker { image 'maven:latest' }
            }
            steps {
                sh 'mvn --version'
            }
        }
        stage('Front-end') {
            agent { 
                docker { image 'node:20-alpine' }
            }
            steps {
                sh 'node --version'
            }
        }
        stage('Database Tier') {
            agent {
                // Uses the official lightweight MySQL image
                docker { image 'mysql:8.0' }
            }
            steps {
                // Checks that the MySQL client software executes correctly inside the container
                sh 'mysql --version'
            }
        }
    }
}
