pipeline {
    agent none
    stages {    
        stage ('Back-end') {
            agent { 
                docker { image 'maven:309.6-eclipse-temurin-11' }
            }
            steps {
                sh 'mvn --version'
            }
        }
        stage ('Front-end') {
            agent { 
                docker { image 'node:20-alpine' }
            }
            steps {
                sh 'node --version'
            }
        }
    }
}
